name: DevSecOps Analyzer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Secret Scanning with Gitleaks
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --no-banner --redact

      # 2. Dependency Scanning (Node.js)
      - name: Run npm audit
        run: |
          if [ -f package-lock.json ]; then
            npm install
            npm audit --json > npm-audit-report.json || true
          fi

      # 3. Dependency Scanning (Python)
      - name: Run pip-audit
        run: |
          if [ -f requirements.txt ]; then
            pip install pip-audit
            pip-audit -r requirements.txt -f json -o pip-audit-report.json || true
          fi

      # 4. Static Analysis (Python - Bandit)
      - name: Run Bandit
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-report.json || true

      # 5. Static Analysis (Multi-lang - Semgrep)
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"

      # 6. Dynamic App Scan (OWASP ZAP Baseline)
      - name: Run OWASP ZAP
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:3000"   # change to your app URL
